#!/bin/bash -l

#SBATCH --nodes=3
#SBATCH --constraint=gpu
#SBATCH --time=06:00:00
#SBATCH --tasks=36
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=12
#SBATCH --cpus-per-task=1
#SBATCH --job-name=assim
#SBATCH --error=impact_error.log
#SBATCH --account=sm56
#SBATCH --partition=normal

srun --ntasks=36 --cpus-per-task=1 --constraint=gpu --output=impact.log --error=impact_error.log --account=sm56  ./impact.exe 
