#!/bin/bash

set -uxo pipefail

rm *.mod *.o mr_io_example_spatial mr_io_test_reader mr_io_test_reader_space_time mr_io_test_reader_hpc_predict mr_io_test_parallel_reader mr_io_test_parallel_reader_space_time mr_io_test_parallel_reader_hpc_predict mr_io_test_parallel_reader_spacetime mr_io_test_reader_writer mr_io_test_parallel_reader_writer mr_io_test_parallel_reader_writer_space_time mr_io_test_parallel_reader_writer_hpc_predict mr_io_test_reader_writer_space_time mr_io_test_reader_writer_hpc_predict mr_io_example_space_time test_file.h5 test_space_time.h5
